package  {
	import flash.display.MovieClip;
	import flash.media.SoundChannel;
	
	
	// TODO: Decouple MovieClip from this class
	// TODO: Rename this class
	public class player extends MovieClip {
		/* MovieClip structure */
		public var gui:MovieClip;
		public var head:MovieClip;
		public var body:MovieClip;
		public var leg1:MovieClip;
		public var leg2:MovieClip;
		public var arm1:MovieClip;
		public var arm2:MovieClip;
		public var toe:MovieClip;

		/* (Formerly dynamic) properties */

		// Atomic (TODO: Add proper types)
		public var mdl3d:*;
		public var info:*;
		public var mp_shot_correct:*;
		public var mp_must_shoot_once:*;
		public var incar:*;
		public var ondeath:*;
		public var onalert:*;

		// Typed
		public var char:int;
		public var charset_by_user:Boolean;
		public var nick_color:uint;
		public var last_say_sound:int;
		public var idd:int;
		public var exp_potential:Number;
		public var side:Number;
		public var hea:Number;
		public var hmax:Number;
		public var real_hea:Number;
		public var last_shoot_chance:Boolean;
		public var boost:Number;
		public var defih:int;
		public var antigravity:Number;
		public var antigravity_radius:Number;
		public var can_be_hit:Boolean;
		public var can_drop_guns:Boolean;
		public var isGhost:Boolean;
		public var voice:Object;
		public var jump_scale:Number;
		public var scale:Number;
		public var sword_spam_strength:Number;
		public var knockback_factor:Number;
		public var regen_speed:Number;
		public var regen_delay:Number;
		public var collideWithOthers:Boolean;
		public var collideWithPlayer:Array;
		public var collideWithTeam:Array;
		public var hero:Boolean;
		public var onhit:int;
		public var textcolorchanged:Boolean;
		public var palette:Array;
		public var mp_controlled:Boolean;
		public var mp_packets:int;
		public var mp_aliveping:int;
		public var mp_time:Number;
		public var mp_x:Number;
		public var mp_y:Number;
		public var mp_tox:Number;
		public var mp_toy:Number;
		public var mp_x2:Number;
		public var mp_y2:Number;
		public var mp_tox2:Number;
		public var mp_toy2:Number;
		public var mp_offset_x:Number;
		public var mp_offset_y:Number;
		public var login_name:String;
		public var last_contact:int;
		public var enemy_vis_tim:int;
		public var lastshot:String;
		public var lastshotby:int;
		public var whenlastshot:int;
		public var lastshotbygun:String;
		public var lastshotbygunid:int;
		public var botaction:int;
		public var io:Boolean;
		public var deadtim:int;
		public var nick:String;
		public var step_sound_phase:Number;
		public var pressure:int;
		public var wep_pause:Number;
		public var voice_channel:SoundChannel;
		public var idle_phase:Number;
		public var moving_speed:Number;
		public var stand:Boolean;
		public var sit:Number;
		public var tox:Number;
		public var toy:Number;
		public var armored:int;
		public var melee_ani:Number;
		public var melee_tim:Number;
		public var tarx:Number;
		public var tary:Number;
		public var regentim:int;
		public var hunt:int;
		public var no_psi:Boolean;
		public var mobility:Number;
		public var team:int;
		public var rand:Number;
		public var rand2:Number;
		public var rand3:Number;
		public var randtim:Number;
		public var act_fire:Boolean;
		public var act_movex:int;
		public var act_movey:int;
		public var act_fall:Boolean;
		public var ltox:Number;
		public var ltoy:Number;
		public var ang:Number;
		public var stability:Number;
		public var curwea:int;
		public var wea_shot:int;
		public var waiting:int;
		public var inwater:Boolean;
		public var dead:Boolean;
		public var blood_red:Number;
		public var blood_green:Number;
		public var blood_blue:Number;
		public var ping:int;
		public var hp_head:Number;
		public var hp_body:Number;
		public var hp_legs:Number;
		public var hp_arms:Number;
		public var brk_head:Boolean;
		public var brk_body:Boolean;
		public var brk_legs:Boolean;
		public var brk_arms:Boolean;
		public var dying:Boolean;
		public var notspawned:Boolean;
		public var notseen:Boolean;
		public var b_toe:int;
		public var b_leg1:int;
		public var b_leg2:int;
		public var b_arm1:int;
		public var b_arm2:int;
		public var b_body:int;
		public var b_brk1:int;
		public var b_brk2:int;
		public var b_head_start:int;
		public var b_head_end:int;
		public var b_p2:int; // REMOVE: NOT SUPPOSED TO BE HERE (fixes a random bug that tries to access b_p2)
		public var ch_leg1_max:int;
		public var ch_leg2_max:int;
		public var ch_leg1_min:int;
		public var ch_leg2_min:int;
		public var ch_leg1_damp:int;
		public var ch_leg2_damp:int;
		public var ch_arm1_max:int;
		public var ch_arm2_max:int;
		public var ch_arm1_min:int;
		public var ch_arm2_min:int;
		public var ch_body:int;
		public var ch_spine:int;
		public var ch_shoulder:int;
		public var ch_head:int;
		public var ch_brk1:int;
		public var ch_brk2:int;
		public var ch_body_ang1:int;
		public var ch_body_ang2:int;
		public var ch_body_ang3:int;
		public var ch_body_ang4:int;
		public var ch_body_ang4b:int;
		public var ch_body_ang5:int;
		public var mdl_toe:int;
		public var mdl_body:int;
		public var mdl_head:int;
		public var mdl_leg1_upper:int;
		public var mdl_leg1_middle:int;
		public var mdl_leg1_lower:int;
		public var mdl_leg2_upper:int;
		public var mdl_leg2_middle:int;
		public var mdl_leg2_lower:int;
		public var mdl_arm1_upper:int;
		public var mdl_arm1_lower:int;
		public var mdl_arm2_upper:int;
		public var mdl_arm2_lower:int;
		public var mdl_psi1:int;
		public var mdl_psi2:int;
		public var effects:Vector.<Object>;
		public var isplayer:Boolean;
		public var arm_nade:int;
		public var startx:Number;
		public var starty:Number;
		public var startteam:int;
		public var startchar:int;
		public var startside:Number;
		public var blames:int = 10;
		public var startbotaction:int;
		public var walk_x:int = 0;
		public var walk_bug:int;
	}
}